### ISSUE TITLE
[FEAT] Implement classes related to configuration files

### ISSUE THREAD

**Issue by kimhxsong** [WeCanWebserv/Webserv#12]
## Description
- #7 에서 임시로 작성했던 클래스들 중 ConfigParser와 ConfigInfo, Locations를 구현합니다.
- ConfigInfo는 구성파일의 모든 내용을 담고 있습니다.
- ConfigParser는 구성파일 경로를 생성자 인자로 받아 해당 경로의 파일을 열고 파일 내용을 객체 자신 버퍼에 씁니다.  getInfo()를 호출하면 버퍼를 읽어 중괄호 단위로 구별되는 서버 블록에 대한 ConfigInfo을 반환합니다. ConfigParser는 ServerManager의 생성자에서 지역변수로 생성되고 소멸됩니다.
- Location은 ConfigInfo가 가지고 있는 맵 컨테이너 타입을 특정하는데,  std::map의 mapped_type으로 사용되며 파싱하는 과정에서 Location 블록 하나가 컨테이너의 데이터 요소 하나로 대응됩니다.

## TO DO
- [x] Implement  `class Location`
- [x] Implement `class Config`
- [ ] Implement `class ConfigParser`

**Comment by kimhxsong** [comment]
Before:
```
http{include mime.types;default_type application/octet-stream;sendfile on;keepalive_timeout 65;server{listen 8080; server_name localhost;location /{root html;index index.html index.htm;}error_page 500 502 503 504  /50x.html;location = /50x.html{root html;}}include servers/*;}
```

Process:
```
replace "{" => "\n{\n"
replace ";" => ";\n"
replace "}" => "\n}\n"
trim
skip empty-line
```

After:
```
http
{
include mime.types;
default_type application/octet-stream;
sendfile on;
keepalive_timeout 65;
server
{
listen 8080;
server_name localhost;
location /
{
root html;
index index.html index.htm;
}
error_page 500 502 503 504  /50x.html;
location = /50x.html
{
root html;
}    
}
include servers/*;
}
```

**Comment by kimhxsong** [comment]
command:
```shell
$> cd {workspace}/webserv/src/Parser.cpp && c++ Parser.cpp && ./a.out
```
output:
```
(feature/#12)⚡ % ./a.out                                                                                                                                                                                                     ~/goinfre/Webserv/webserv/src
@ Global
worker_processes  1
@ Http
include mime.types
default_type application/octet-stream
sendfile on
keepalive_timeout 65
include servers/*
@ Server
listen 8080
server_name localhost
error_page 500 502 503 504  /50x.html
@ Location
root html
index index.html index.htm
```

**Comment by kimhxsong** [comment]
## Todo
- [x] trim 구현. 일단 빠른 구현을 위해 boost 라이브러리의 trim()을 사용했습니다.
- [x] '#' 주석 처리 수정. 주석처리 된 행의 가장 마지막 문자가 '{'일 때 의도한대로 동작하지 않습니다.
- [x] 하위 컨테스트를 둘 이상 파싱. 현재는 둘 이상의 server 블럭, location 블럭을 처리하지 못합니다.

**Comment by kimhxsong** [comment]
command:
```shell
$> cd {workspace}/webserv/src/Parser.cpp && c++ Parser.cpp && ./a.out
```
output:
```
(feature/#12)⚡ % ./a.out                                                                                                                                                                                                     ~/goinfre/Webserv/webserv/src
@ Global
        worker_processes  1
@ Http
        include mime.types
        default_type application/octet-stream
        sendfile on
        keepalive_timeout 65
        include servers/*
@ Server
        listen 8080
        server_name localhost
        error_page 500 502 503 504  /50x.html
@ Location
path: /
        root html
        index index.html index.htm
path: /upload
        root html
```

**Comment by kimhxsong** [comment]
output:
```
(feature/#12)⚡ % ./a.out                                                                                                                                                                                                                                    ~/goinfre/Webserv/webserv/src
@ Global
        worker_processes  1

@ Http
        include mime.types
        default_type application/octet-stream
        sendfile on
        keepalive_timeout 65
        include servers/*

        @ Servers[0]
                listen 8080
                server_name localhost
                error_page 500 502 503 504  /50x.html

                @ location [/]
                        root html
                        index index.html index.htm
                @ location [/upload]
                        root html
                        index index.html index.htm
        @ Servers[1]
                listen 80
                server_name example.com
                error_page 500 502 503 504  /50x.html

                @ location [/]
                        root html
                        index index.html index.htm
                @ location [/download]
                        root html
                        index index.html index.htm
```

**Comment by kimhxsong** [comment]
done: https://github.com/WeCanWebserv/Webserv/issues/12#issuecomment-1230261152

**Comment by kimhxsong** [comment]
```
(feature/#12)⚡ % ./a.out                                             ~/goinfre/Webserv/webserv/src
Server info/version: wcw/0.0.1

[42] ServerConfiguration
maxRquestBodySize: 10240
address:port : 
        [0]: 127.0.0.1:4242
        [1]: 127.0.0.1:8080

Server Names: 
        [0]: example.com
        [1]: www.example.com

[/] Location Configuration
Index Files: 
        [0]: index.html
        [1]: index.htm

CGI Support: 
        [.php]: /usr/local/opt/php
        [.py]: /usr/local/opt/python@3.10

CGI Uploads: 
        [.py]: /usr/local/upload

Error Pages: 
        [501]: /error/50x.html
        [502]: /error/50x.html

```

**Comment by kimhxsong** [comment]
## Todo
~~-  serverFd, configBlock 을 멀티맵으로 관리.~~
~~서버 블럭을 순서대로 읽고 처리하는데 listen 하는 host, port가 중복되는 경우 기존 소켓을 재사용하도록 처리.~~
~~일부 구조를 multimap으로 변경한 후 ServerMananger 생성자를 재작성하는데, 문제가 발견되지 않으면 vector<std::string>을 Config 클래스로 변환하는 클래스 또는 함수 작성.~~
- [x] 에러 페이지는 Location 블록이 아닌 Server Block context에서 파싱되도록 변경

**Comment by kimhxsong** [comment]
## Todo

- [x] ServerBlock에 데이터를 파싱할 때 컨테이너의 back() 메소드를 사용하지 않고 currentBlock과 같은 데이터 멥버를 *Block 클래스에 추가하여 파싱이 끝난 후 컨테이너 객체에 insert하도록 수정
- [ ] 파싱한 블럭들을 Config 클래스 객체로 변환하는 멤버 함수 구현

**Comment by kimhxsong** [comment]
## ToFix
- [x] ft_trim(...)
